/* ============================================================
   species_atlas.js — GENERATED by tools/build_species_atlas.py.
   ------------------------------------------------------------
   Do not hand-edit: rerun the tool. It reads the 30 hand-drawn ant sprites in
   assets/source-sprites and writes both this table and the sheet it describes.

   The existing 6x4 assets/ants_atlas.png is untouched and still drives the four
   roles. This is additive: 30 species, laid out small to large, with
   walk and carry at the same columns as the old sheet so the two are
   interchangeable.
   ============================================================ */

const SPECIES_SPRITE = {
  src: 'assets/ants_species_atlas.png',
  cell: 64, cols: 12, rows: 30,
    walk: [0, 1, 2],
  carry: [3, 4, 5],
  attack: [6, 7, 8],
  idle: [9, 10, 11],
  fps: 9,
};

/* Row order is the atlas's row order — small ants first. */
const ANT_SPECIES = [
  {
    "id": "electric-ant",
    "name": "Electric ant",
    "size": "small",
    "row": 0
  },
  {
    "id": "fire-ant",
    "name": "Fire ant",
    "size": "small",
    "row": 1
  },
  {
    "id": "ghost-ants",
    "name": "Ghost ants",
    "size": "small",
    "row": 2
  },
  {
    "id": "green-ant",
    "name": "Green ant",
    "size": "small",
    "row": 3
  },
  {
    "id": "little-black",
    "name": "Little Black",
    "size": "small",
    "row": 4
  },
  {
    "id": "medic-ant",
    "name": "Medic ant",
    "size": "small",
    "row": 5
  },
  {
    "id": "red-ants",
    "name": "Red ants",
    "size": "small",
    "row": 6
  },
  {
    "id": "thief-ants",
    "name": "Thief ants",
    "size": "small",
    "row": 7
  },
  {
    "id": "white-footed-ants",
    "name": "White-footed ants",
    "size": "small",
    "row": 8
  },
  {
    "id": "acrobat-ants",
    "name": "Acrobat ants",
    "size": "medium",
    "row": 9
  },
  {
    "id": "big-headed-ants",
    "name": "Big-headed ants",
    "size": "medium",
    "row": 10
  },
  {
    "id": "bulldog-ants",
    "name": "Bulldog ants",
    "size": "medium",
    "row": 11
  },
  {
    "id": "driver-ants",
    "name": "Driver Ants",
    "size": "medium",
    "row": 12
  },
  {
    "id": "field-ants",
    "name": "Field ants",
    "size": "medium",
    "row": 13
  },
  {
    "id": "honey-ants",
    "name": "Honey ants",
    "size": "medium",
    "row": 14
  },
  {
    "id": "odorous-ants",
    "name": "Odorous ants",
    "size": "medium",
    "row": 15
  },
  {
    "id": "pavement-ants",
    "name": "Pavement ants",
    "size": "medium",
    "row": 16
  },
  {
    "id": "tiger-ants",
    "name": "Tiger ants",
    "size": "medium",
    "row": 17
  },
  {
    "id": "yellow-meadow-ant",
    "name": "Yellow Meadow Ant",
    "size": "medium",
    "row": 18
  },
  {
    "id": "argentine-ants",
    "name": "Argentine ants",
    "size": "large",
    "row": 19
  },
  {
    "id": "army-ants",
    "name": "Army ants",
    "size": "large",
    "row": 20
  },
  {
    "id": "bullet-ant",
    "name": "Bullet ant",
    "size": "large",
    "row": 21
  },
  {
    "id": "carpenter-ants",
    "name": "Carpenter ants",
    "size": "large",
    "row": 22
  },
  {
    "id": "crazy-ants",
    "name": "Crazy ants",
    "size": "large",
    "row": 23
  },
  {
    "id": "doctor-ant",
    "name": "Doctor ant",
    "size": "large",
    "row": 24
  },
  {
    "id": "dracula-ants",
    "name": "Dracula ants",
    "size": "large",
    "row": 25
  },
  {
    "id": "harvester-ants",
    "name": "Harvester ants",
    "size": "large",
    "row": 26
  },
  {
    "id": "leafcutter-ants",
    "name": "Leafcutter ants",
    "size": "large",
    "row": 27
  },
  {
    "id": "pharaoh-ants",
    "name": "Pharaoh ants",
    "size": "large",
    "row": 28
  },
  {
    "id": "turtle-ants",
    "name": "Turtle ants",
    "size": "large",
    "row": 29
  }
];
